// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensorsControl.Repositories.EntityFrameworkCore;

#nullable disable

namespace SensorsControl.Repositories.Migrations
{
    [DbContext(typeof(SensorsControlContext))]
    [Migration("20230831114433_MyMigration")]
    partial class MyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SensorsControl.Repositories.Entities.DailyTelemetryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyTelemetryEntities");
                });

            modelBuilder.Entity("SensorsControl.Repositories.Entities.TelemetryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<float>("Illum")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DailyEntityId");

                    b.ToTable("TelemetryEntities");
                });

            modelBuilder.Entity("SensorsControl.Repositories.Entities.TelemetryEntity", b =>
                {
                    b.HasOne("SensorsControl.Repositories.Entities.DailyTelemetryEntity", "DailyEntity")
                        .WithMany("DailyRecords")
                        .HasForeignKey("DailyEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyEntity");
                });

            modelBuilder.Entity("SensorsControl.Repositories.Entities.DailyTelemetryEntity", b =>
                {
                    b.Navigation("DailyRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
